name: Weekly Google Reviews

on:
  schedule:
    # Runs every Monday at 15:00 UTC (which is 9:00 AM Denver when on MDT)
    - cron: "0 15 * * 1"
  workflow_dispatch: {} # lets you run it manually from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Recreate the service account file from the secret you already added
      - name: Write service account file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/service_account.json" >> $GITHUB_ENV

      - name: Run script
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # optional
        run: |
          python reviews.py

      # Optional: keep outputs/logs from each run
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-output
          path: |
            reports/**
            *.log
          if-no-files-found: ignore
